### ISSUE TITLE
Major Feature: 1.0 Release

### ISSUE THREAD

**Issue by corey-f1v** [f1v/hrbot#93]
Can you guys focus on finishing up all commands besides paymo and releasing it for people to use in Slack? I think it'd be awesome for people to start immediately being able to set vacation days and stuff

**Comment by davidholyko** [comment]
Yes. I'll have to work with Fabio for figuring out why the actual prod hrbot doesnt listen.

**Comment by davidholyko** [comment]
We  will need to switch to actual spreadsheet  from Veiko, Fabio

**Comment by davidholyko** [comment]
Features

```
Sick 
  Half-day support
Vacation
  Vacation Ranges
  Half-day support
Paymo Integration
```

**Comment by davidholyko** [comment]
Closed as redundant
